GEMINI_API_KEY = "AIzaSyCyWMPTl3CFKVQDnrwdjPepNEZIIno6fOE"
OPENAI_API_KEY = "..."
#"#
#[credentials.usernames.janed]
#email = "jane@example.com"
#name = "Jane Doe"
#password = "$2b$12$UOv0jSyK6/RgKIoN7hTCIu8AzROsP2mNYJYcOP/6xCjpyJ9FX8Yxi"
#
#[credentials.usernames.jdoe]
#email = "jdoe@example.com"
#name = "John Doe"
#password = "$2b$12$zRllx1N36sL7OEK5hv7EMuFJhKEXuQvTpMEGz4yp78xgfIVRT9HTa"  # just an example
#
#[cookie]
#name = "pdfcompare_app"
#key = "super_secret_key"
#expiry_days = 30
#
#[preauthorized]
#emails = ["jane@example.com", "jdoe@example.com"]
#"